# Generated by Django 5.0 on 2024-01-02 21:06

import crackem.crack.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Name cannot be less than 2 characters!'), django.core.validators.MaxLengthValidator(20, 'Name cannot exceeds 20 characters!'), crackem.crack.validators.names_with_alphas])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Name cannot be less than 2 characters!'), django.core.validators.MaxLengthValidator(20, 'Name cannot exceeds 20 characters!'), crackem.crack.validators.names_with_alphas])),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Name cannot be less than 2 characters!'), django.core.validators.MaxLengthValidator(20, 'Name cannot exceeds 20 characters!')])),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(6, 'Password cannot be less than 6 characters'), django.core.validators.MaxLengthValidator(10, 'password cannot be more than 10 characters')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
            ],
        ),
    ]
