# Generated by Django 5.0 on 2024-01-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
