# Generated by Django 5.0 on 2024-01-06 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crack', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, 'Password cannot be less than 6 characters'), django.core.validators.MaxLengthValidator(10, 'password cannot be more than 10 characters')]),
        ),
    ]
